reclamation_index:
    path:     /
    defaults: { _controller: "ReclamationBundle:Reclamation:index" }
    methods:  GET

reclamation_show:
    path:     /{idPub}/show
    defaults: { _controller: "ReclamationBundle:Reclamation:show" }
    methods:  GET

reclamation_new:
    path:     /new
    defaults: { _controller: "ReclamationBundle:Reclamation:new" }
    methods:  [GET, POST]

reclamation_edit:
    path:     /{idPub}/edit
    defaults: { _controller: "ReclamationBundle:Reclamation:edit" }
    methods:  [GET, POST]

reclamation_delete:
    path:     /{idPub}/delete
    defaults: { _controller: "ReclamationBundle:Reclamation:delete" }
    methods:  DELETE
